// Code generated by rice embed-go; DO NOT EDIT.
package migrate

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "1_create_table_user.down.sql",
		FileModTime: time.Unix(1627492855, 0),

		Content: string("DROP TABLE \"user\";"),
	}
	file3 := &embedded.EmbeddedFile{
		Filename:    "1_create_table_user.up.sql",
		FileModTime: time.Unix(1627492857, 0),

		Content: string("-- Table Definition ----------------------------------------------\n\nCREATE TABLE \"user\" (\n    id text,\n    name text,\n    created_at timestamp with time zone,\n    updated_at timestamp with time zone,\n    deleted_at timestamp with time zone\n);"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1627492854, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "1_create_table_user.down.sql"
			file3, // "1_create_table_user.up.sql"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`./files`, &embedded.EmbeddedBox{
		Name: `./files`,
		Time: time.Unix(1627492854, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"1_create_table_user.down.sql": file2,
			"1_create_table_user.up.sql":   file3,
		},
	})
}
